spring.application.name=proyecto
#configuración para la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/aprendiz
spring.datasource.username=root
spring.datasource.password=

#configuración hibernate
spring.jpa.show-sql:true
spring.jpa.hibernate.ddl-auto:update