spring.application.name=proyecto

# Configuración para la base de datos (con variables de entorno)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:aprendiz}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# Configuración hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update